- hosts: all
  become: true

  tasks:
    - name: Install the unzip package
      apt:
        name: unzip
        state: present

    - name: Download and extract Consul in /bin
      unarchive:
        src: https://releases.hashicorp.com/consul/1.0.6/consul_1.0.6_linux_amd64.zip
        dest: /bin/
        remote_src: yes

    - name: Make default config directory
      command: sudo mkdir /etc/consul.d

    - name: Launch Consul.
      shell: nohup /bin/consul agent -dev </dev/null >/dev/null 2>&1 &
